# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: George Brown College - OpenSource Club
email: info@gbos.club
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/gbos-club" # the subpath of your site, e.g. /blog
url: "http://gbos.club" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: George Brown OpenSource

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 9
paginate_path: /page:num/

analytics:
disqus-shortname: gbopensource

#social
facebook: http://facebook.com/webjeda
quora: http://quora.com/sharathdt
twitter: http://twitter.com/@webjeda
github: http://github.com/webjeda
slack: http://gbos.slack.com

#facebook like box
fb-app-id:
fb-page-url:
fb-page-title: SCIT Students


sass:
  style: compressed

gems: [jekyll-paginate, jekyll-seo-tag]
